### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by Nicolai-Holmgaard** [Ortygia/Deaftone#11]
I cound't find the repo for the site, so I will just say it here.
On the frontpage of the website.
"Deaftone is a fast free opensrouce music server. Looking to rival Roon in metadata"
Opensource is misspelled.

Btw, its a nice project, I wish you good luck with it!

**Comment by awnnshikaa** [comment]
Please assign me this issue.

**Comment by awnnshikaa** [comment]
Please assign me this issue.

**Comment by awnnshikaa** [comment]
@Nicolai-Holmgaard  Could you please put a label on this issue.

**Comment by Nicolai-Holmgaard** [comment]
I belive i cant do that.

**Comment by awnnshikaa** [comment]
@Nicolai-Holmgaard Oh.. i see
