### ISSUE TITLE
error: failed to select a version for the requirement `axum = "^0.6.1"`

### ISSUE THREAD

**Issue by meh-me** [Ortygia/Deaftone#13]
I cloned the repository locally and uses cargo build to build the app and when I do it gives me this error

    Updating crates.io index
error: failed to select a version for the requirement `axum = "^0.6.1"`
candidate versions found which didn't match: 0.5.17, 0.5.16, 0.5.15, ...
location searched: crates.io index
required by package `deaftone v0.0.1 (/Deaftone)`

I'm running this on  proxmox CT with ubuntu 22.04 LTS

**Comment by 112RG** [comment]
Try updating the repo with and running ``rm -rf  ~/.cargo/registry`` the cargo registry might be corrupted

**Comment by meh-me** [comment]
> rm -rf ~/.cargo/registry

I did that, still getting the same error

**Comment by 112RG** [comment]
I don't reproduce this issue. I am on a clean Ubuntu VM using ``rustc 1.68.0-nightly`` and I am not getting this issue.

what version of rust is yours? Do ``rustc --version``

**Comment by meh-me** [comment]
I'm using `rustc 1.58.1`

**Comment by 112RG** [comment]
I would try using the latest rust stable or nightly

**Comment by 112RG** [comment]
Sorry something I forgot to add is the MSRV (Minimum supported Rust version) is 1.65 or newer

**Comment by meh-me** [comment]
I did `apt update && apt upgrade rustc` but I'm still at rustc 1.61.0

**Comment by meh-me** [comment]
I used the rustup installer script to install it and now it is on 1.68.0-nightly
